### ISSUE TITLE
Does not work with wdio 3.2.5

### ISSUE THREAD

**Issue by electricmonk** [webdriverio/browserevent#5]
When initializing `browserevent` with an instance of WebDriverIO 3.2.5, I get this exception:

```
     undefined: Cannot set property 'removeEventListener' of undefined
```

The code initializing it:

``` js
                this.browser = webdriverio.remote({
                    host: "localhost",
                    port: seleniumPort,
                    desiredCapabilities: { browserName: 'chrome' }
                });

                browserevent.init(this.browser);
```

I see that there are major changes in object structure between 2.x and 3.x, could this be related?

**Comment by christian-bromann** [comment]
That's what the readme is saying in its first sentence 😉 .. browserevent only runs with WebdriverIO v 2.x .. I hope I can update this package soon but this is low prio.. PRs welcome though

**Comment by electricmonk** [comment]
You got me.
This page, however, has no mention of this incompatibility:
http://webdriver.io/guide/plugins/browserevent.html

**Comment by christian-bromann** [comment]
Good point, I will update that

**Comment by Petah** [comment]
"soon"

![soon](https://i.ytimg.com/vi/yuiNlr6oZvU/maxresdefault.jpg)

Meanwhile we are up to v4 now.

**Comment by christian-bromann** [comment]
Like I said it is low prio and was actually more an experiment than an actual project. If you need it feel free to contribute!
